# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_pastas.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserFilesScreen(object):
 
    def loadData(self, lista, tabela):
            tabela.setRowCount(0)
            self.buttons = []
            print(lista)
            self.infos = []
            for row_number in range(len(lista)):
                tabela.insertRow(row_number)
                tabela.setItem(row_number, 0, QtWidgets.QTableWidgetItem(lista[row_number][1]))
                tabela.setItem(row_number, 1, QtWidgets.QTableWidgetItem(lista[row_number][2]))
                tabela.setItem(row_number, 2, QtWidgets.QTableWidgetItem(str(lista[row_number][3])))
                tabela.setItem(row_number, 3, QtWidgets.QTableWidgetItem(str(lista[row_number][4])))
                self.infos.append(lista[row_number])
         
                self.buttons.append(QtWidgets.QPushButton(tabela))
                self.buttons[-1].setText("Baixar")
                self.buttons[-1].setStyleSheet("background-color: #345995;\n"
                "color: #FFFFFF;")
                tabela.setCellWidget(row_number, 4, self.buttons[-1])

    def setupUi(self, UserFilesScreen):
        UserFilesScreen.setObjectName("UserFilesScreen")
        UserFilesScreen.setWindowModality(QtCore.Qt.NonModal)
        UserFilesScreen.resize(916, 615)
        UserFilesScreen.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        UserFilesScreen.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(UserFilesScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.uploadButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploadButton.setGeometry(QtCore.QRect(390, 560, 181, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 255, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 255, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 255, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.uploadButton.setPalette(palette)
        self.uploadButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uploadButton.setStyleSheet("selection-background-color: rgb(110, 255, 188);")
        self.uploadButton.setObjectName("uploadButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-5, 10, 21, 431))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 54, 51))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 30, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.version_app = QtWidgets.QLabel(self.centralwidget)
        self.version_app.setGeometry(QtCore.QRect(830, 570, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.version_app.setFont(font)
        self.version_app.setObjectName("version_app")
        self.foto_perfil = QtWidgets.QLabel(self.centralwidget)
        self.foto_perfil.setGeometry(QtCore.QRect(820, 10, 54, 41))
        self.foto_perfil.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.foto_perfil.setText("")
        self.foto_perfil.setPixmap(QtGui.QPixmap("imagesQT/person.png"))
        self.foto_perfil.setObjectName("foto_perfil")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(800, 50, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 100, 871, 451))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 871, 421))
        self.tableWidget.setMinimumSize(QtCore.QSize(871, 421))
        self.tableWidget.setMaximumSize(QtCore.QSize(871, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 871, 421))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 0, 871, 421))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(5)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, 0, 871, 421))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(5)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_5.setGeometry(QtCore.QRect(0, 0, 871, 421))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(5)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_6.setGeometry(QtCore.QRect(0, 0, 871, 421))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(5)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(4, item)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_7.setGeometry(QtCore.QRect(0, 0, 871, 421))
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(5)
        self.tableWidget_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(4, item)
        self.tabWidget.addTab(self.tab_6, "")
        UserFilesScreen.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(UserFilesScreen)
        self.statusbar.setObjectName("statusbar")
        UserFilesScreen.setStatusBar(self.statusbar)

        self.retranslateUi(UserFilesScreen)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UserFilesScreen)

    def retranslateUi(self, UserFilesScreen):
        _translate = QtCore.QCoreApplication.translate
        UserFilesScreen.setWindowTitle(_translate("UserFilesScreen", "MainWindow"))
        self.uploadButton.setText(_translate("UserFilesScreen", "Upload"))
        self.label_2.setText(_translate("UserFilesScreen", "<html><head/><body><p><img src=\"logoShare.png\"/></p></body></html>"))
        self.label_3.setText(_translate("UserFilesScreen", "DriveShare"))
        self.version_app.setText(_translate("UserFilesScreen", "Versão 1.0"))
        self.label.setText(_translate("UserFilesScreen", "Marcos Paulo"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("UserFilesScreen", "Arquivo"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("UserFilesScreen", "Tipo"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("UserFilesScreen", "Tamanho(B)"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("UserFilesScreen", "Data"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("UserFilesScreen", "Ações"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("UserFilesScreen", "Recentes"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("UserFilesScreen", "Arquivo"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("UserFilesScreen", "Tipo"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("UserFilesScreen", "Tamanho(B)"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("UserFilesScreen", "Data"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("UserFilesScreen", "Ações"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("UserFilesScreen", "Documentos"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("UserFilesScreen", "Arquivo"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("UserFilesScreen", "Tipo"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("UserFilesScreen", "Tamanho(B)"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("UserFilesScreen", "Data"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("UserFilesScreen", "Ações"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("UserFilesScreen", "Imagens"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("UserFilesScreen", "Arquivo"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("UserFilesScreen", "Tipo"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("UserFilesScreen", "Tamanho(B)"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("UserFilesScreen", "Data"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("UserFilesScreen", "Ações"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("UserFilesScreen", "Vídeos"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("UserFilesScreen", "Arquivo"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("UserFilesScreen", "Tipo"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("UserFilesScreen", "Tamanho(B)"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("UserFilesScreen", "Data"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("UserFilesScreen", "Ações"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("UserFilesScreen", "Músicas"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("UserFilesScreen", "Arquivo"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("UserFilesScreen", "Tipo"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("UserFilesScreen", "Tamanho(B)"))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("UserFilesScreen", "Data"))
        item = self.tableWidget_6.horizontalHeaderItem(4)
        item.setText(_translate("UserFilesScreen", "Ações"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("UserFilesScreen", "Compartilhados"))
        item = self.tableWidget_7.horizontalHeaderItem(0)
        item.setText(_translate("UserFilesScreen", "Arquivo"))
        item = self.tableWidget_7.horizontalHeaderItem(1)
        item.setText(_translate("UserFilesScreen", "Tipo"))
        item = self.tableWidget_7.horizontalHeaderItem(2)
        item.setText(_translate("UserFilesScreen", "Tamanho(B)"))
        item = self.tableWidget_7.horizontalHeaderItem(3)
        item.setText(_translate("UserFilesScreen", "Data"))
        item = self.tableWidget_7.horizontalHeaderItem(4)
        item.setText(_translate("UserFilesScreen", "Ações"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("UserFilesScreen", "Outros"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserFilesScreen = QtWidgets.QMainWindow()
    ui = Ui_UserFilesScreen()
    ui.setupUi(UserFilesScreen)
    UserFilesScreen.show()
    sys.exit(app.exec_())
done