# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_pastas.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserFilesScreen(object):
    def setupUi(self, UserFilesScreen):
        UserFilesScreen.setObjectName("UserFilesScreen")
        UserFilesScreen.setWindowModality(QtCore.Qt.NonModal)
        UserFilesScreen.resize(916, 615)
        UserFilesScreen.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        UserFilesScreen.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(UserFilesScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.SearchButtom = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButtom.setGeometry(QtCore.QRect(730, 90, 81, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 200, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 200, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 200, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 200, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 200, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 200, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 200, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 200, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 200, 29))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.SearchButtom.setPalette(palette)
        self.SearchButtom.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SearchButtom.setStyleSheet("background-color: rgb(46, 200, 29);")
        self.SearchButtom.setObjectName("SearchButtom")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(180, 130, 701, 431))
        self.treeView.setObjectName("treeView")
        self.uploadButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploadButton.setGeometry(QtCore.QRect(820, 90, 81, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 255, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 255, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 255, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.uploadButton.setPalette(palette)
        self.uploadButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uploadButton.setStyleSheet("selection-background-color: rgb(110, 255, 188);")
        self.uploadButton.setObjectName("uploadButton")
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(880, 130, 21, 431))
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.menu_files = QtWidgets.QTreeWidget(self.centralwidget)
        self.menu_files.setGeometry(QtCore.QRect(20, 130, 161, 431))
        self.menu_files.setObjectName("menu_files")
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.menu_files.headerItem().setFont(0, font)
        self.menu_files.headerItem().setBackground(0, QtGui.QColor(89, 215, 114))
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.menu_files.headerItem().setForeground(0, brush)
        item_0 = QtWidgets.QTreeWidgetItem(self.menu_files)
        font = QtGui.QFont()
        font.setPointSize(12)
        item_0.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.menu_files)
        font = QtGui.QFont()
        font.setPointSize(12)
        item_0.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.menu_files)
        font = QtGui.QFont()
        font.setPointSize(12)
        item_0.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.menu_files)
        font = QtGui.QFont()
        font.setPointSize(12)
        item_0.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.menu_files)
        font = QtGui.QFont()
        font.setPointSize(12)
        item_0.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.menu_files)
        font = QtGui.QFont()
        font.setPointSize(12)
        item_0.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.menu_files)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-5, 10, 21, 431))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.progress_share = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_share.setGeometry(QtCore.QRect(40, 500, 101, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(245, 121, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 121, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 121, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.progress_share.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.progress_share.setFont(font)
        self.progress_share.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progress_share.setProperty("value", 74)
        self.progress_share.setOrientation(QtCore.Qt.Horizontal)
        self.progress_share.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progress_share.setObjectName("progress_share")
        self.file_searc_input = QtWidgets.QTextEdit(self.centralwidget)
        self.file_searc_input.setGeometry(QtCore.QRect(20, 90, 701, 31))
        self.file_searc_input.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.file_searc_input.setObjectName("file_searc_input")
        self.count_files = QtWidgets.QLabel(self.centralwidget)
        self.count_files.setGeometry(QtCore.QRect(50, 470, 81, 17))
        self.count_files.setObjectName("count_files")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 54, 51))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 30, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.progress_upload = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_upload.setGeometry(QtCore.QRect(310, 570, 331, 21))
        self.progress_upload.setProperty("value", 24)
        self.progress_upload.setObjectName("progress_upload")
        self.version_app = QtWidgets.QLabel(self.centralwidget)
        self.version_app.setGeometry(QtCore.QRect(830, 570, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.version_app.setFont(font)
        self.version_app.setObjectName("version_app")
        self.foto_perfil = QtWidgets.QLabel(self.centralwidget)
        self.foto_perfil.setGeometry(QtCore.QRect(820, 10, 54, 41))
        self.foto_perfil.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.foto_perfil.setText("")
        self.foto_perfil.setPixmap(QtGui.QPixmap("imagesQT/person.png"))
        self.foto_perfil.setObjectName("foto_perfil")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(800, 50, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        UserFilesScreen.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(UserFilesScreen)
        self.statusbar.setObjectName("statusbar")
        UserFilesScreen.setStatusBar(self.statusbar)

        self.retranslateUi(UserFilesScreen)
        QtCore.QMetaObject.connectSlotsByName(UserFilesScreen)

    def retranslateUi(self, UserFilesScreen):
        _translate = QtCore.QCoreApplication.translate
        UserFilesScreen.setWindowTitle(_translate("UserFilesScreen", "MainWindow"))
        self.SearchButtom.setText(_translate("UserFilesScreen", "Buscar"))
        self.treeView.setToolTip(_translate("UserFilesScreen", "<html><head/><body><p><br/></p></body></html>"))
        self.uploadButton.setText(_translate("UserFilesScreen", "Upload"))
        self.menu_files.headerItem().setText(0, _translate("UserFilesScreen", "      Meus Arquivos"))
        __sortingEnabled = self.menu_files.isSortingEnabled()
        self.menu_files.setSortingEnabled(False)
        self.menu_files.topLevelItem(0).setText(0, _translate("UserFilesScreen", "Documentos"))
        self.menu_files.topLevelItem(1).setText(0, _translate("UserFilesScreen", "Músicas"))
        self.menu_files.topLevelItem(2).setText(0, _translate("UserFilesScreen", "Fotos"))
        self.menu_files.topLevelItem(3).setText(0, _translate("UserFilesScreen", "Vídeos"))
        self.menu_files.topLevelItem(4).setText(0, _translate("UserFilesScreen", "Compartilhados"))
        self.menu_files.topLevelItem(5).setText(0, _translate("UserFilesScreen", "Outros"))
        self.menu_files.setSortingEnabled(__sortingEnabled)
        self.count_files.setText(_translate("UserFilesScreen", "897 Arquivos"))
        self.label_2.setText(_translate("UserFilesScreen", "<html><head/><body><p><img src=\"logoShare.png\"/></p></body></html>"))
        self.label_3.setText(_translate("UserFilesScreen", "DriveShare"))
        self.version_app.setText(_translate("UserFilesScreen", "Versão 1.0"))
        self.label.setText(_translate("UserFilesScreen", "Marcos Paulo"))
# import imageLogo_rc
# import logo_user_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserFilesScreen = QtWidgets.QMainWindow()
    ui = Ui_UserFilesScreen()
    ui.setupUi(UserFilesScreen)
    UserFilesScreen.show()
    sys.exit(app.exec_())
done